version: '3'
services:
      proxy:
            image: nginx:alpine # utilise la version la plus récente 
            ports:
                  - '80:80' # expose 80 sur l’hôte et envoie à 80 dans conteneur 
            networks:
                  - frontend
            volumes:
                  - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

      
      php1:
            build: './php/'
            networks:
                  - backend1
            restart: on-failure
            environment:
                  MON_SERVEUR:      Serveur1 - PHP1 - TP2
                  MON_HOST:   MariaDB1
            volumes:
                  - ./monsite/html:/usr/local/apache2/htdocs/
                  #- ./monsite/html:/var/www/html
      php2:
            build: './php/'
            networks:
                  - backend2
            restart: on-failure
            environment:
                  MON_SERVEUR:      Serveur2 - PHP2 - TP2
                  MON_HOST:   MariaDB2
            volumes:
                  - ./monsite/html:/usr/local/apache2/htdocs/
                  #- ./monsite/html:/var/www/html


#sudo chown -R $USER <path-to-folder>
      serveur1:
            image: httpd:alpine # utilise la version httpd:lapine 
            # depends_on:
            #       - php1
            #       - mariadb1
            networks:
                  - frontend
                  - backend1
            volumes:
                  - ./monsite/html:/usr/local/apache2/htdocs
                  - ./serveur1/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      serveur2:
            image: httpd:alpine # utilise la version httpd:alpine 
            # depends_on:
            #       - php2
            #       - mariadb2
            networks:
                  - frontend
                  - backend2
            volumes:
                  - ./monsite/html:/usr/local/apache2/htdocs
                  - ./serveur2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf


      mariadb1:
            image: mariadb:latest
            networks:
                  - backend1
            environment:
                  #- MYSQL_ROOT_USER=root
                  - MYSQL_ROOT_PASSWORD=rootpassword
                  #- MYSQL_DATABASE=tp2_media_web
                  #- MYSQL_USER=admin
                  #- MYSQL_PASSWORD=rootpassword
            restart: on-failure
            volumes:
                  - ./serveur1/mariadb/dbdata:/var/lib/mysql
                  - ./monsite/SQL/init.sql:/docker-entrypoint-initdb.d/init.sql
      mariadb2:
            image: mariadb:latest
            networks:
                  - backend2
            environment:
                  #- MYSQL_ROOT_USER=root
                  - MYSQL_ROOT_PASSWORD=rootpassword
                  #- MYSQL_DATABASE=tp2_media_web
                  #- MYSQL_USER=admin
                  #- MYSQL_PASSWORD=rootpassword
            restart: on-failure
            volumes:
                  - ./serveur2/mariadb/dbdata:/var/lib/mysql
                  - ./monsite/SQL/init.sql:/docker-entrypoint-initdb.d/init.sql


networks:
      frontend:
      backend1:
      backend2: